version: '3'

services:
  nuxt:
    container_name: nuxt
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "npm i --silent && npm run dev"
    tty: true
    stdin_open: true